### ISSUE TITLE
Add hamburger side menu for the mobile version.

### ISSUE THREAD

**Issue by jpalacio0612** [jpalacio0612/react-neon-ui-demo#1]
We currently have this fixed menu for the mobile version:

![image](https://user-images.githubusercontent.com/65427911/135694236-d2ea28d6-1e73-487d-8317-e5395f539311.png)

You can check the demo in [https://react-neon-ui-demo.vercel.app/](url)

This issue is about turning this vertical menu into a hamburger side menu that appears from one side only in the mobile version. You can take the following menu as an example:

![image](https://user-images.githubusercontent.com/65427911/135695524-dead38ef-0adb-4d9d-bfd0-d64768696106.png)

**Comment by daptheHuman** [comment]
can you assign it to me? 
let me try
