### ISSUE TITLE
Add the new Divider component to the demo and documentation

### ISSUE THREAD

**Issue by jpalacio0612** [jpalacio0612/react-neon-ui-demo#17]
A new component called "Divider" has been added to the react-neon-ui library [https://github.com/jpalacio0612/react-neon-ui](https://github.com/jpalacio0612/react-neon-ui). We need to add this new component to the demo with its proper documentation. Take as reference the components that are already added.

![image](https://user-images.githubusercontent.com/65427911/138597308-90453c1b-dbe9-4d0b-b096-9948819c2bb7.png)

**Comment by odorifqi** [comment]
i would like to try this, can you assign this to me?

**Comment by jpalacio0612** [comment]
@odorifqi Ok, go ahead!

**Comment by odorifqi** [comment]
Are you sure the `{ Divider }` already added to the library? because i'm unable to add it to the documentation page. Please let me know if i missed something.

**Comment by jpalacio0612** [comment]
@odorifqi Excuse me, we had some problems with the export of the component, but it has already been solved, you can try with the new version of react-neon-ui

**Comment by odorifqi** [comment]
@jpalacio0612 cool, thanks for the info, will try

**Comment by jpalacio0612** [comment]
Closed by (#21)
