### ISSUE TITLE
Add the new TextArea component to the demo and documentation

### ISSUE THREAD

**Issue by jpalacio0612** [jpalacio0612/react-neon-ui-demo#18]
A new component called "TextArea" has been added to the react-neon-ui library [https://github.com/jpalacio0612/react-neon-ui](https://github.com/jpalacio0612/react-neon-ui). We need to add this new component to the demo with its proper documentation. Take as reference the components that are already added.

![image](https://user-images.githubusercontent.com/65427911/138608941-325ed6ab-0e9c-421e-9602-09b523976780.png)

**Comment by kiennguyenchi** [comment]
Hi, I would like to give a try on this. Could you please assign the issue to me and specify which file I am working on? Thank you!

**Comment by jpalacio0612** [comment]
@kiennguyenchi Sure, You have to create a new view in the demo, similar to the [TextInput](https://react-neon-ui-demo.vercel.app/textinput) but using the TextArea component, to import the TextArea you just have to do it like this:

```javascript
import { TextArea } from 'react-neon-ui'
```

is it clear?

**Comment by kiennguyenchi** [comment]
Just want to clarify. For TextArea component, we create 'Text Area' on left navigation bar. When click on it, there will be "General" tab and "use cases" tab as well, right?

And where do I get documentation for TextArea? I cannot find it in snippets.js

**Comment by jpalacio0612** [comment]
@kiennguyenchi Exactly, the documentation is the same as the `TextInput` component, you can create snippets similar to those of `TextInput`.

**Comment by kiennguyenchi** [comment]
Please review my PR #20 and let me know for any feedback. I import TextArea component, use TextArea components and TextInputSnippets but it does not seem to work.

**Comment by jpalacio0612** [comment]
Ok, that happens because you have an old version of the library installed, so you are going to do the following:

- Delete the `node_modules` folder from your project
- Go to `package.json`, find the react-neon-ui library and put the version: `"react-neon-ui": "^1.0.19",`
- Run `npm install` to install all dependencies.

**Comment by kiennguyenchi** [comment]
Thank you! It worked now, could you please check my PR #20 ?
