### ISSUE TITLE
[BUG] - It fails when trying to enter the URL directly without going through the home page.

### ISSUE THREAD

**Issue by jpalacio0612** [jpalacio0612/react-neon-ui-demo#2]
When for example I try to enter directly to: [https://react-neon-ui-demo.vercel.app/button](url) the following error appears: 

![image](https://user-images.githubusercontent.com/65427911/135696092-68505fda-7de3-4865-8223-b80a6537e770.png)

but if I enter from home [https://react-neon-ui-demo.vercel.app/](url) and navigate with the links to the different views it works correctly. Maybe it's some problem with the webpack or react-router-dom configuration.

**Comment by edenriquez** [comment]
I just created this PR https://github.com/jpalacio0612/react-neon-ui-demo/pull/3 that solves the problem, I add this gif as reference
![fix](https://user-images.githubusercontent.com/26972091/135699179-45faeabb-b286-47ad-84c9-51f95ca44a68.gif)
